[package]
name = "snake"
version = "0.1.0"
edition = "2021"

[dependencies]
rand = "0.9.0"
rodio = "0.20.1"
sdl2 = {version ="0.37.0", features = ["ttf", "image"] }
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
